gateways:
  local:
    connection:
      type: postgres
      host: ${POSTGRES_HOST}
      port: 5432
      database: ${POSTGRES_DB}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

default_gateway: local

model_defaults:
  dialect: postgres
  start: 2024-09-06s