gateways:
  local:
    connection:
      type: postgres
      host: ${{ secrets.POSTGRES_HOST}}
      port: 5432
      database: ${{ secrets.POSTGRES_DB}}
      user: ${{ secrets.POSTGRES_USER}}
      password: ${{ secrets.POSTGRES_PASSWORD}}

default_gateway: local

model_defaults:
  dialect: postgres
  start: 2024-09-06s